/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "heoxdoxnerzlubfmnjaw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhlb3hkb3huZXJ6bHViZm1uamF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0MTA4MTYsImV4cCI6MjA4MTk4NjgxNn0.tH-4qrZLBUMMsT6GYiHdy-SbyMw7O4netU4UzHnPssc"